name: Build and Deploy .NET MAUI App

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    # Set up .NET SDK
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    # Install .NET MAUI workload
    - name: Install .NET MAUI
      run: dotnet workload install maui

    # Restore dependencies
    - name: Restore dependencies
      run: dotnet restore

    # Decode and save keystore file
    - name: Decode keystore
      run: |
        echo "${{ secrets.ANDROID_KEYSTORE }}" | base64 --decode > studentshelper.keystore

    # Build and sign the project
    - name: Build and sign APK
      run: |
        dotnet publish StudentsHelper/StudentsHelper.csproj -c Release -f net9.0-android -o ./app-build/ /p:AndroidKeyStore=true /p:AndroidSigningKeyStore=studentshelper.keystore /p:AndroidSigningKeyAlias=studentshelper /p:AndroidSigningKeyPass=${{ secrets.KEY_PASSWORD }} /p:AndroidSigningStorePass=${{ secrets.STORE_PASSWORD }}

    # Create APK file and publish to the specified output folder
    - name: Publish APK to GitHub Releases
      run: |
        dotnet publish StudentsHelper/StudentsHelper.csproj -c Release -f net9.0-android -o ./app-build/
        echo "APK published"

    # Rename APK file to StudentsHelper.apk
    - name: Rename APK to StudentsHelper.apk
      run: |
        move ./app-build/*.apk ./app-build/StudentsHelper.apk

    # Create a new release tag and upload renamed APK to GitHub Releases
    - name: Create Release and Upload APK
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v1.0.${{ github.run_number }}
        files: ./app-build/StudentsHelper.apk
        token: ${{ secrets.GH_TOKEN }}